version: '3'

services:
  manager:
    image: fenchelfen/namenode:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      san:

  storagenode:
    depends_on:
      - manager
    image: fenchelfen/storagenode:latest
    ports:
      - "9999:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    networks:
      san:


  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  san:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24
