version: '3'

services:
  manager:
    image: fenchelfen/namenode
    #    build:
    #      context: .
    #      dockerfile: namenode/Dockerfile
    ports:
      - "9999:80"
    networks:
      san:
        ipv4_address: 192.168.77.3
        aliases:
          - namenode
      hostonly:
#    volumes:
#      - ./:/workdir
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  storagenode:
    depends_on:
      - manager
    image: fenchelfen/storagenode
    #    build:
    #      context: .
    #      dockerfile: storagenode/Dockerfile
    ports:
      - "8081:80"
    networks:
      san:
      hostonly:
#    volumes:
#      - ./:/workdir
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]


  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
  san:
    internal: true
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24
  hostonly:
